#ifndef __CONFIG_H__
#define __CONFIG_H__

// EEPROM address
#define ENCODER_SCALE_ADDRESS 1
#define IS_ENCODER_MODE_ADDRESS 2
#define PULSE_PER_MM_ADDRESS 3 // &4
#define REVERSE_ENCODER_ADDRESS 5
#define PULSE_PER_MM_CONVEYOR_ADDRESS 6 // &7
#define REVERSE_CONVEYOR_ADDRESS 8
#define IS_CONVEYOR_MODE_ADDRESS 9
#define IS_RUN_WITH_ENCODER_ADDRESS 10
#define IS_AUTO_RUN_SPEED_ADDRESS 11
#define AUTO_RUN_SPEED_ADDRESS 12 // &13
#define ETHERNET_PORT_ADDRESS 14
#define ETHERNET_IP_ADDRESS 15
#define ETHERNET_DNS_ADDRESS 19
#define ETHERNET_GATEWAY_ADDRESS 23
#define ETHERNET_SUBNET_ADDRESS 27
#define ETHERNET_MAC_ADDRESS 31 // &36
#define TIME_AUTO_FEEDBACK_ADDRESS 37
#define CONVEYOR_ACCEL_ADDRESS 38 // &39
#define SPEED_WHEN_RUN_WITH_BUTTON_ADDRESS 40 // &41
#define ETHERNET_ENABLE_ADDRESS 42
#define DEVICE_NAME_ADDRESS 43
#define UUID_ADDRESS 67
#define FIRMWARE_VERSION_ADDRESS 87
#define BOARD_VERSION_ADDRESS 93
#define SERIAL_NUMBER_ADDRESS 99

// Default values
#define DEFAULT_DEVICE_NAME "Desktop X Conveyor V1.0"
#define DEFAULT_UUID "0005-0000-0000-0001"
#define DEFAULT_FIRMWARE_VERSION "1.0.0"
#define DEFAULT_BOARD_VERSION "1.0.0"
#define DEFAULT_SERIAL_NUMBER "0001"
#define DEFAULT_PORT 8844

#define DEFAULT_MAX_SPEED 500
#define DEFAULT_READ_POTENTIOMETER_PERIOD 100
#define DEFAULT_MIN_SPEED 10

#endif // __CONFIG_H__