#ifndef __CONFIG_H__
#define __CONFIG_H__

// EEPROM address
#define ENCODER_SCALE_ADDRESS 1
#define IS_ENCODER_MODE_ADDRESS 2
#define PULSE_PER_MM_ADDRESS 3 // &4
#define REVERSE_ENCODER_ADDRESS 5
#define PULSE_PER_MM_CONVEYOR_ADDRESS 6 // &7
#define REVERSE_CONVEYOR_ADDRESS 8
#define IS_CONVEYOR_MODE_ADDRESS 9
#define IS_RUN_WITH_ENCODER_ADDRESS 10
#define IS_AUTO_RUN_SPEED_ADDRESS 11
#define AUTO_RUN_SPEED_ADDRESS 12 // &13
#define ETHERNET_PORT_ADDRESS 14
#define ETHERNET_IP_ADDRESS 16
#define ETHERNET_DNS_ADDRESS 20
#define ETHERNET_GATEWAY_ADDRESS 24
#define ETHERNET_SUBNET_ADDRESS 28
#define ETHERNET_MAC_ADDRESS 32 // &37
#define TIME_AUTO_FEEDBACK_ADDRESS 38
#define CONVEYOR_ACCEL_ADDRESS 39 // &40
#define SPEED_WHEN_RUN_WITH_BUTTON_ADDRESS 41 // &42
#define ETHERNET_ENABLE_ADDRESS 43 
#define CONVEYOR_ADDRESS 44 // &45

#define DEFAULT_PORT 8844
#define FIRMWARE_DATE "14/10/2025"
#define DEFAULT_MAX_SPEED 500
#define DEFAULT_READ_POTENTIOMETER_PERIOD 100
#define DEFAULT_MIN_SPEED 10

#endif // __CONFIG_H__