#pragma once

#define ENCODER_A_PIN PA11
#define ENCODER_B_PIN PA12

#define LED_RUN_PIN PA0
#define LED_FUNC_PIN PA1

#define MOTOR_PUL_PIN PB6
#define MOTOR_DIR_PIN PB7
#define MOTOR_EN_PIN PB5

#define ETH_RESET_PIN PA3
#define ETH_CS_PIN PA4
#define ETH_MISO_PIN PA6
#define ETH_MOSI_PIN PA7
#define ETH_SCK_PIN PA5

#define POTENTIOMETER_PIN PB0

#define CAN_CS_PIN PB11
#define CAN_INT_PIN PB8
#define CAN_MISO_PIN PB14
#define CAN_MOSI_PIN PB15
#define CAN_SCK_PIN PB13

#define TX2_PIN PA2
#define RX2_PIN PA3

#define TX3_PIN PB10
#define RX3_PIN PB11

#define ENCODER_SCALE_ADDRESS 1
#define IS_ENCODER_MODE_ADDRESS 2
#define PULSE_PER_MM_ADDRESS 3 // &4
#define REVERSE_ENCODER_ADDRESS 5

#define PULSE_PER_MM_CONVEYOR_ADDRESS 6 // &7
#define REVERSE_CONVEYOR_ADDRESS 8
#define IS_CONVEYOR_MODE_ADDRESS 9
#define IS_RUN_WITH_ENCODER_ADDRESS 10

#define IS_AUTO_RUN_SPEED_ADDRESS 11
#define AUTO_RUN_SPEED_ADDRESS 12 // &13

#define ETHERNET_PORT_ADDRESS 14
#define ETHERNET_IP_ADDRESS 15
#define ETHERNET_DNS_ADDRESS 19
#define ETHERNET_GATEWAY_ADDRESS 23
#define ETHERNET_SUBNET_ADDRESS 27
#define ETHERNET_MAC_ADDRESS 31 // &36

#define TIME_AUTO_FEEDBACK_ADDRESS 37

#define CONVEYOR_ACCEL_ADDRESS 38 // &39

#define SPEED_WHEN_RUN_WITH_BUTTON_ADDRESS 40 // &41

#define ETHERNET_ENABLE_ADDRESS 42


#define DEFAULT_DEVICE_NAME "Desktop X Conveyor V1.0"
#define DEFAULT_UUID "0005-0000-0000-0001"
#define DEFAULT_FIRMWARE_VERSION "1.0.0"
#define DEFAULT_BOARD_VERSION "1.0.0"
#define DEFAULT_SERIAL_NUMBER "0001"
#define DEFAULT_PORT 8844

#define DEVICE_NAME_ADDRESS 43
#define UUID_ADDRESS 67
#define FIRMWARE_VERSION_ADDRESS 87
#define BOARD_VERSION_ADDRESS 93
#define SERIAL_NUMBER_ADDRESS 99