#pragma once

#define ENCODER_A_PIN PB7
#define ENCODER_B_PIN PB6

#define INPUT_1_PIN PA12
#define INPUT_2_PIN PA11
#define INPUT_3_PIN PB14
#define INPUT_4_PIN PB13

#define LED_RUN_PIN PA8
#define LED_FUNC_PIN PB15

#define MOTOR_PUL_PIN PB8
#define MOTOR_DIR_PIN PB9
#define MOTOR_EN_PIN PB5

#define OUTPUT_1_PIN PB12
#define OUTPUT_2_PIN PA2
#define OUTPUT_3_PIN PA1
#define OUTPUT_4_PIN PA0

#define ETH_RESET_PIN PA3
#define IS_ETH_ENABLE_ADDRESS 0
#define ENCODER_SCALE_ADDRESS 1
#define IS_ENCODER_MODE_ADDRESS 2
#define PULSE_PER_MM_ADDRESS 3 // &4
#define REVERSE_ENCODER_ADDRESS 5

#define PULSE_PER_MM_CONVEYOR_ADDRESS 6 // &7
#define REVERSE_CONVEYOR_ADDRESS 8
#define IS_CONVEYOR_MODE_ADDRESS 9
#define IS_RUN_WITH_ENCODER_ADDRESS 10

#define IS_AUTO_RUN_SPEED_ADDRESS 11
#define AUTO_RUN_SPEED_ADDRESS 12 // &13

#define ETHERNET_PORT_ADDRESS 14
#define ETHERNET_IP_ADDRESS 16
#define ETHERNET_DNS_ADDRESS 20
#define ETHERNET_GATEWAY_ADDRESS 24
#define ETHERNET_SUBNET_ADDRESS 28
#define ETHERNET_MAC_ADDRESS 32 // &36

#define TIME_AUTO_FEEDBACK_ADDRESS 38

#define CONVEYOR_ACCEL_ADDRESS 39 // &40

#define SPEED_WHEN_RUN_WITH_BUTTON_ADDRESS 41 // &42

#define CONVEYOR_ADDRESS 43 // &44
#define INPUT_FUNCTION_ADDRESS 45 // 45..48 (function code of 4 inputs)
#define INPUT_VALUE_ADDRESS 49    // 49..64 (value of 4 inputs, 4 bytes each)
#define OUTPUT_FUNCTION_ADDRESS 65 // 65..68 (function code of 4 outputs)
#define OUTPUT_VALUE_ADDRESS 69    // 69..84 (value of 4 outputs, 4 bytes each)
#define POS_SPEED_ADDRESS 85       // 85..88 (position move speed M313, raw float)

#define MAIN_BOARD_VERSION "2.0"

#define FIRMWARE_DATE "20/7/2026"
#define FIRMWARE_VERSION "2.0.0"


